// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVJn3JezE30TdL7rYFvjin6Wu1FhKd3WA',
    appId: '1:755480191862:web:8847c3499a1ffc37e55057',
    messagingSenderId: '755480191862',
    projectId: 'mobile-app-backend-34fee',
    authDomain: 'mobile-app-backend-34fee.firebaseapp.com',
    storageBucket: 'mobile-app-backend-34fee.appspot.com',
    measurementId: 'G-EJ9BBX2T4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0opNX0dBgQToh65NSMeDKgW0CzyAcA-s',
    appId: '1:755480191862:android:0963602f5d1144e8e55057',
    messagingSenderId: '755480191862',
    projectId: 'mobile-app-backend-34fee',
    storageBucket: 'mobile-app-backend-34fee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0m3HrUWrJPzY-MLLkjXtjldwR2q-jrn0',
    appId: '1:755480191862:ios:fd2fd33c5ae00d7ae55057',
    messagingSenderId: '755480191862',
    projectId: 'mobile-app-backend-34fee',
    storageBucket: 'mobile-app-backend-34fee.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0m3HrUWrJPzY-MLLkjXtjldwR2q-jrn0',
    appId: '1:755480191862:ios:d15f775b727c56f9e55057',
    messagingSenderId: '755480191862',
    projectId: 'mobile-app-backend-34fee',
    storageBucket: 'mobile-app-backend-34fee.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
